### ISSUE TITLE
Selectboxes are collapsing right after displaying (Mac OS, Firefox)

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#140]
**Current status:**
When I choosing option in administration via selectbox (e.g. choosing articles in Admin > Settings > Legal conditions > Legal conditions). Sometimes (in 25% cases) when I click to open selectbox, the option appears and immediatly disapperas as if I choose option. 

It happens only on FF, Chrome is OK. I wasn't able to create valid steps to reproduce.

**Comment by boris-brtan** [comment]
I notice the same thing when i touch the scroll mouse pad. Could this be the same issue?

**Comment by kulincz** [comment]
I tried to replicate this issue but wit no result. Maybe it is already fixed. I have Mac and Firefox 61.0.2 .. please try if this problem is actual. Thank you.

**Comment by topolanekmartin** [comment]
Issue can not be replicated. Please check if problem persist.

I attach links where were discussed similar issue directly on Firefox official websites:
- https://support.mozilla.org/cs/questions/1161166
- https://support.mozilla.org/cs/questions/1106010

**Comment by boris-brtan** [comment]
some insight from testing, there is some functionality for osX when we hold click over selectbox selected option can be changed and after click release selectbox will close.

**Comment by LukasHeinz** [comment]
It doesn't occur any more. I close issue because I created it
