### ISSUE TITLE
problem with sending emails in CLI

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#728]
### What is happening

In CLI mode like cron etc. there could be issue with swiftmailer spool if cron crash, because emails are send only onTerminate event and that event is not called on exception (https://github.com/symfony/swiftmailer-bundle/blob/master/EventListener/EmailSenderListener.php#L46).

Example: 
1. I run command php phing cron
2. First module sends new registered users to IS and sends email to user
2. Cron say that it sent emails to new users
3. Next cron module throws exception for some unknown reason
4. All emails that should be send are away 

### Expected result

If i call $mailer->send($message), that email should be sent immediately.

**Comment by simara-svatopluk** [comment]
The proposed solution is a change of behavior, could it be solved in a different fashion? Does Symfony provide an event that occurs on exception that could be used as fallback for sending e-mails?

**Comment by henzigo** [comment]
Hello @simara-svatopluk 
Thank you for your reaction. You could probably override that EmailSenderListener, but i dont think that this is right way. There is another way, that you can configure swiftmailer to save spool to file, but you will need to send email manualy (cron) https://symfony.com/doc/3.4/email/spool.html . Anyway i still think, that the best way is remove spool, because its only change config.

**Comment by henzigo** [comment]
I also think that this config was created a long time ago and nobody cared about how it works until now. This is probably the best logical solution for me, because you send emails after some action was successfully processed and you do not want wait if another part of program fails.

**Comment by boris-brtan** [comment]
this seems like problem of missing documentation or something and what is more like we have 
`packages/framework/src/Model/Mail/Mailer.php`
```php
$successSend = $this->swiftMailer->send($message, $failedRecipients);
if (!$successSend && count($failedRecipients) > 0) {
     throw new 
     \Shopsys\FrameworkBundle\Model\Mail\Exception\SendMailFailedException($failedRecipients);
}
```
Does this function make sense? it could be called for example from `Shopsys\FrameworkBundle\Model\Customer\Mail\CustomerMailFacade\sendRegistrationMail`

**Comment by vitek-rostislav** [comment]
Solved by https://github.com/shopsys/shopsys/pull/875, will be released in `v8.0.0` as the solution introduces a bc break.

**Comment by henzigo** [comment]
Hello, I'm sorry I missed this implementation. This issue is not solved for me because you fixed only my example, but there are other situations that are not covered by your implementation. 

Another Example:

1. I run the command `php phing cron`
2. The module sends newly registered users to IS and sends email to user
3. 20 users are registered in IS and emails were sent 
4. Next user throws an error
5. All emails that should be send are away

**Comment by grossmannmartin** [comment]
Hi, @henzigo 
thanks for another scenario to test. 
Maybe you could use information in documentation – https://docs.shopsys.com/en/8.0/introduction/faq-and-common-issues/#why-are-e-mails-sent-before-end-of-the-script-and-not-immediately

If I understand correctly, the problem occurs when in the middle of your cron module, the exception is thrown.
So you suggest removing spooling completely?

**Comment by henzigo** [comment]
Yes, I suggest removing spooling because you don't have to find out that your emails are not sent for a long time.

For me is worse to have this feature here than remove it.

**Comment by vitek-rostislav** [comment]
Hi, I agree with @henzigo, with the current setting, it might be very hard to find out why your emails are not sent (it happened to us :smile:)

**Comment by henzigo** [comment]
Hello, any news about this issue?

**Comment by pk16011990** [comment]
Hi, I still want disable spooling. Better to send a few extra emails than less/nothing.

**Comment by TomasLudvik** [comment]
Hello, I have suggestion how this could be solved to everyones satisfaction. Lets have:
- method for immediate email send
- method for saving email to spool
- method for flushing such spool
- method for emptying spool
- method for removing 1 concrete email from spool.

You could then decide if you want to send email immediately or you wanna work with spool that you will manage and flush / empty it on exception / error.

What do you guys think?

**Comment by pk16011990** [comment]
Currently, we don't use Swiftmailler with spooling, and It's no longer relevant with Symfony/mailer.
