### ISSUE TITLE
Javascript constraint validation of email should use same regex as server does.

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#747]
### What is happening
Currently, there is a very simple regular expression in javascript for checking email and really complex is used on the server. 

This might result in different behavior on the server and on the client.

Affected file is `./packages/framework/src/Resources/scripts/common/validation/ShopsysShopBundleComponentConstraintsEmail.js`

### Expected result
The same regular expression should be used on the server and on the client.

**Comment by PetrHeinz** [comment]
I believe that currently, the JS contraint validator is not even used properly due to non-matching name of the JS function `ShopsysFrameworkBundleComponentConstraintsEmail` and the PHP validator `\Shopsys\FrameworkBundle\Form\Constraints\Email`. This is fixed in #648 (d7773e199953fd298221d5047a9c8bacb7cf3d52).

**Comment by PetrHeinz** [comment]
This issue might have been fixed by #829, can anyone verify this?

**Comment by grossmannmartin** [comment]
Nope, still present on master.
"email" address – `\\@shoh.co` – is valid according to JS validation and then denied with server-side validation.

**Comment by grossmannmartin** [comment]
closed by #2346
