### ISSUE TITLE
Run tests with different Redis database

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#860]
### What is happening
Tests are running on the same database as the shop is running.
Tests first cleans the DB (the shop cache), and then runs themselves - so they are not affected by cache state but can affect the shop after they finishes. And just cleaning cache after tests finishes is not optimal solution in my opinion.

### Expected result
Tests should run in different DB than shop.

**Comment by PetrHeinz** [comment]
Could this be achieved just by setting Redis prefix in parameters for `test` environment?

**Comment by simara-svatopluk** [comment]
Yep, and also by using different DB

**Comment by simara-svatopluk** [comment]
Using prefix can have an issue with sessions... maybe?

**Comment by PetrHeinz** [comment]
On demoshop, I've fixed this using a prefix in build version like this: https://github.com/shopsys/demoshop/pull/47/commits/07a1968d56a1d94c578359adee533dba173699a1.

**Comment by pk16011990** [comment]
.

**Comment by vitek-rostislav** [comment]
This issue is still up-to-date. On our project, we use cached Twig blocks (e.g. categories menu). After I run the build (to be more precise, smoke tests), I switch to dev environment, and I see that all the links in the categories menu point to URL `webserver:8000` (the one that is used in test env. Cleaning redis cache solves this problem.

**Comment by s3tezsky** [comment]
fixed in #1985
